// <auto-generated />
using System;
using DhSport.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DhSport.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260101195450_AddSiteLogTable")]
    partial class AddSiteLogTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DhSport.Domain.Entities.Business.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdminNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("admin_note");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dttm");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("create_user_id");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerNm")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_nm");

                    b.Property<string>("CustomerTel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("customer_tel");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ReservationDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reservation_dttm");

                    b.Property<string>("ReservationNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reservation_note");

                    b.Property<string>("ReservationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reservation_status");

                    b.Property<string>("ReservationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reservation_type");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_dttm");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("update_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reservation");

                    b.HasIndex("ReservationDttm")
                        .HasDatabaseName("ix_reservation_reservation_dttm");

                    b.HasIndex("ReservationStatus")
                        .HasDatabaseName("ix_reservation_reservation_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reservation_user_id");

                    b.ToTable("reservation", (string)null);
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Content.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowAnonymous")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_anonymous");

                    b.Property<bool>("AllowComment")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_comment");

                    b.Property<string>("BoardDesc")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("board_desc");

                    b.Property<string>("BoardNm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("board_nm");

                    b.Property<string>("BoardSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("board_slug");

                    b.Property<Guid>("BoardTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_type_id");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dttm");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("create_user_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("PostsPerPage")
                        .HasColumnType("integer")
                        .HasColumnName("posts_per_page");

                    b.Property<bool>("RequireApproval")
                        .HasColumnType("boolean")
                        .HasColumnName("require_approval");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_dttm");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("update_user_id");

                    b.HasKey("Id")
                        .HasName("pk_board");

                    b.HasIndex("BoardSlug")
                        .IsUnique()
                        .HasDatabaseName("ix_board_board_slug");

                    b.HasIndex("BoardTypeId")
                        .HasDatabaseName("ix_board_board_type_id");

                    b.ToTable("board", (string)null);
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Content.BoardType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BoardTypeDesc")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("board_type_desc");

                    b.Property<string>("BoardTypeNm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("board_type_nm");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dttm");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("create_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_dttm");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("update_user_id");

                    b.HasKey("Id")
                        .HasName("pk_board_type");

                    b.HasIndex("BoardTypeNm")
                        .IsUnique()
                        .HasDatabaseName("ix_board_type_board_type_nm");

                    b.ToTable("board_type", (string)null);
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Content.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<object>("CommentContent")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("comment_content");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dttm");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("LikeCnt")
                        .HasColumnType("integer")
                        .HasColumnName("like_cnt");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_comment_id");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_dttm");

                    b.HasKey("Id")
                        .HasName("pk_comment");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("ix_comment_parent_comment_id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_comment_post_id");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Content.CommentLike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dttm");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_comment_like");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comment_like_user_id");

                    b.HasIndex("CommentId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_comment_like_comment_id_user_id");

                    b.ToTable("comment_like", (string)null);
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Content.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_id");

                    b.Property<int>("CommentCnt")
                        .HasColumnType("integer")
                        .HasColumnName("comment_cnt");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dttm");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("create_user_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsNotice")
                        .HasColumnType("boolean")
                        .HasColumnName("is_notice");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean")
                        .HasColumnName("is_secret");

                    b.Property<int>("LikeCnt")
                        .HasColumnType("integer")
                        .HasColumnName("like_cnt");

                    b.Property<string>("MetaDesc")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("meta_desc");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("meta_keywords");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("meta_title");

                    b.Property<object>("PostContent")
                        .HasColumnType("jsonb")
                        .HasColumnName("post_content");

                    b.Property<string>("PostSlug")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("post_slug");

                    b.Property<Guid>("PostTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_type_id");

                    b.Property<DateTime?>("PublishDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publish_dttm");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_dttm");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("update_user_id");

                    b.Property<int>("ViewCnt")
                        .HasColumnType("integer")
                        .HasColumnName("view_cnt");

                    b.HasKey("Id")
                        .HasName("pk_post");

                    b.HasIndex("BoardId")
                        .HasDatabaseName("ix_post_board_id");

                    b.HasIndex("IsPublished")
                        .HasDatabaseName("ix_post_is_published");

                    b.HasIndex("PostSlug")
                        .HasDatabaseName("ix_post_post_slug");

                    b.HasIndex("PostTypeId")
                        .HasDatabaseName("ix_post_post_type_id");

                    b.HasIndex("PublishDttm")
                        .HasDatabaseName("ix_post_publish_dttm");

                    b.ToTable("post", (string)null);
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Content.PostFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dttm");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("PostFileNm")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("post_file_nm");

                    b.Property<string>("PostFilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("post_file_path");

                    b.Property<float>("PostFileSize")
                        .HasColumnType("real")
                        .HasColumnName("post_file_size");

                    b.Property<string>("PostFileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("post_file_type");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.HasKey("Id")
                        .HasName("pk_post_file");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_post_file_post_id");

                    b.ToTable("post_file", (string)null);
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Content.PostLike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dttm");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_post_like");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_post_like_user_id");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_post_like_post_id_user_id");

                    b.ToTable("post_like", (string)null);
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Content.PostRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dttm");

                    b.Property<string>("PostContent")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("post_content");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<string>("RevisionNote")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("revision_note");

                    b.Property<Guid>("RevisionUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("revision_user_id");

                    b.HasKey("Id")
                        .HasName("pk_post_revision");

                    b.HasIndex("CreateDttm")
                        .HasDatabaseName("ix_post_revision_create_dttm");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_post_revision_post_id");

                    b.ToTable("post_revision", (string)null);
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Content.PostType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dttm");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("create_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PostTypeDesc")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("post_type_desc");

                    b.Property<string>("PostTypeNm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("post_type_nm");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_dttm");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("update_user_id");

                    b.HasKey("Id")
                        .HasName("pk_post_type");

                    b.HasIndex("PostTypeNm")
                        .IsUnique()
                        .HasDatabaseName("ix_post_type_post_type_nm");

                    b.ToTable("post_type", (string)null);
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Content.RelatedPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dttm");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("create_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<Guid>("RelatedPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_post_id");

                    b.HasKey("Id")
                        .HasName("pk_related_post");

                    b.HasIndex("RelatedPostId")
                        .HasDatabaseName("ix_related_post_related_post_id");

                    b.HasIndex("PostId", "RelatedPostId")
                        .IsUnique()
                        .HasDatabaseName("ix_related_post_post_id_related_post_id");

                    b.ToTable("related_post", (string)null);
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Features.AddFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dttm");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("create_user_id");

                    b.Property<string>("FeatureContent")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("feature_content");

                    b.Property<Guid>("FeatureTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("feature_type_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_dttm");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("update_user_id");

                    b.HasKey("Id")
                        .HasName("pk_add_feature");

                    b.HasIndex("FeatureTypeId")
                        .HasDatabaseName("ix_add_feature_feature_type_id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_add_feature_post_id");

                    b.ToTable("add_feature", (string)null);
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Features.FeatureType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dttm");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("create_user_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("FeatureTypeDesc")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("feature_type_desc");

                    b.Property<string>("FeatureTypeNm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("feature_type_nm");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_dttm");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("update_user_id");

                    b.HasKey("Id")
                        .HasName("pk_feature_type");

                    b.HasIndex("FeatureTypeNm")
                        .IsUnique()
                        .HasDatabaseName("ix_feature_type_feature_type_nm");

                    b.ToTable("feature_type", (string)null);
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Features.LikeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dttm");

                    b.Property<Guid>("LikeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("like_user_id");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.HasKey("Id")
                        .HasName("pk_like_log");

                    b.HasIndex("PostId", "LikeUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_like_log_post_id_like_user_id");

                    b.ToTable("like_log", (string)null);
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Features.ReadLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dttm");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<Guid?>("ReadUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("read_user_id");

                    b.HasKey("Id")
                        .HasName("pk_read_log");

                    b.HasIndex("CreateDttm")
                        .HasDatabaseName("ix_read_log_create_dttm");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_read_log_post_id");

                    b.ToTable("read_log", (string)null);
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Site.MediaLib", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("alt_text");

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("caption");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dttm");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("create_user_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MediaFileNm")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("media_file_nm");

                    b.Property<string>("MediaFilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("media_file_path");

                    b.Property<float>("MediaFileSize")
                        .HasColumnType("real")
                        .HasColumnName("media_file_size");

                    b.Property<string>("MediaFileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("media_file_type");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_dttm");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("update_user_id");

                    b.HasKey("Id")
                        .HasName("pk_media_lib");

                    b.HasIndex("CreateDttm")
                        .HasDatabaseName("ix_media_lib_create_dttm");

                    b.HasIndex("MediaFileNm")
                        .HasDatabaseName("ix_media_lib_media_file_nm");

                    b.ToTable("media_lib", (string)null);
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Site.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dttm");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("create_user_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MenuIcon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("menu_icon");

                    b.Property<string>("MenuNm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("menu_nm");

                    b.Property<string>("MenuUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("menu_url");

                    b.Property<Guid?>("ParentMenuId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_menu_id");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_dttm");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("update_user_id");

                    b.HasKey("Id")
                        .HasName("pk_menu");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("ix_menu_display_order");

                    b.HasIndex("ParentMenuId")
                        .HasDatabaseName("ix_menu_parent_menu_id");

                    b.ToTable("menu", (string)null);
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Site.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dttm");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("NotificationContent")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notification_content");

                    b.Property<string>("NotificationTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("notification_title");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("notification_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification");

                    b.HasIndex("CreateDttm")
                        .HasDatabaseName("ix_notification_create_dttm");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notification_user_id");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("ix_notification_user_id_is_read");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Site.SiteConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigDesc")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("config_desc");

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("config_value");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dttm");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("create_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_dttm");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("update_user_id");

                    b.HasKey("Id")
                        .HasName("pk_site_config");

                    b.HasIndex("ConfigKey")
                        .IsUnique()
                        .HasDatabaseName("ix_site_config_config_key");

                    b.ToTable("site_config", (string)null);
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Site.SiteLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_id");

                    b.Property<DateTime>("CurrTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("curr_timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CurrUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("curr_url");

                    b.Property<string>("CurrUrlId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("curr_url_ud");

                    b.Property<string>("PrevUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("prev_url");

                    b.Property<string>("PrevUrlId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("prev_url_id");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("session_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_site_log");

                    b.HasIndex("CurrTimestamp")
                        .HasDatabaseName("ix_site_log_curr_timestamp");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_site_log_session_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_site_log_user_id");

                    b.ToTable("site_log", (string)null);
                });

            modelBuilder.Entity("DhSport.Domain.Entities.UserManagement.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dttm");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("create_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("RoleDesc")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("role_desc");

                    b.Property<string>("RoleNm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role_nm");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_dttm");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("update_user_id");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("RoleNm")
                        .IsUnique()
                        .HasDatabaseName("ix_role_role_nm");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("DhSport.Domain.Entities.UserManagement.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dttm");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("create_user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastLoginDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_dttm");

                    b.Property<string>("LogonId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("logon_id");

                    b.Property<string>("Passwd")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("passwd");

                    b.Property<string>("ProfileImg")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("profile_img");

                    b.Property<string>("Tel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tel");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_dttm");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("update_user_id");

                    b.Property<string>("UserNm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_nm");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.HasIndex("LogonId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_logon_id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("DhSport.Domain.Entities.UserManagement.UserRoleMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_dttm");

                    b.Property<Guid?>("CreateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("create_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_dttm");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("update_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_role_map");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_map_role_id");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_role_map_user_id_role_id");

                    b.ToTable("user_role_map", (string)null);
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Content.Board", b =>
                {
                    b.HasOne("DhSport.Domain.Entities.Content.BoardType", "BoardType")
                        .WithMany("Boards")
                        .HasForeignKey("BoardTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_board_board_types_board_type_id");

                    b.Navigation("BoardType");
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Content.Comment", b =>
                {
                    b.HasOne("DhSport.Domain.Entities.Content.Comment", "ParentComment")
                        .WithMany("ChildComments")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_comment_comment_parent_comment_id");

                    b.HasOne("DhSport.Domain.Entities.Content.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_posts_post_id");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Content.CommentLike", b =>
                {
                    b.HasOne("DhSport.Domain.Entities.Content.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_like_comments_comment_id");

                    b.HasOne("DhSport.Domain.Entities.UserManagement.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_like_users_user_id");

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Content.Post", b =>
                {
                    b.HasOne("DhSport.Domain.Entities.Content.Board", "Board")
                        .WithMany("Posts")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_board_board_id");

                    b.HasOne("DhSport.Domain.Entities.Content.PostType", "PostType")
                        .WithMany("Posts")
                        .HasForeignKey("PostTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_post_types_post_type_id");

                    b.Navigation("Board");

                    b.Navigation("PostType");
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Content.PostFile", b =>
                {
                    b.HasOne("DhSport.Domain.Entities.Content.Post", "Post")
                        .WithMany("Files")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_file_post_post_id");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Content.PostLike", b =>
                {
                    b.HasOne("DhSport.Domain.Entities.Content.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_like_post_post_id");

                    b.HasOne("DhSport.Domain.Entities.UserManagement.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_like_users_user_id");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Content.PostRevision", b =>
                {
                    b.HasOne("DhSport.Domain.Entities.Content.Post", "Post")
                        .WithMany("Revisions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_revision_post_post_id");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Content.RelatedPost", b =>
                {
                    b.HasOne("DhSport.Domain.Entities.Content.Post", "Post")
                        .WithMany("RelatedPostsFrom")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_related_post_post_post_id");

                    b.HasOne("DhSport.Domain.Entities.Content.Post", "RelatedToPost")
                        .WithMany("RelatedPostsTo")
                        .HasForeignKey("RelatedPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_related_post_post_related_post_id");

                    b.Navigation("Post");

                    b.Navigation("RelatedToPost");
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Features.AddFeature", b =>
                {
                    b.HasOne("DhSport.Domain.Entities.Features.FeatureType", "FeatureType")
                        .WithMany("Features")
                        .HasForeignKey("FeatureTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_add_feature_feature_types_feature_type_id");

                    b.HasOne("DhSport.Domain.Entities.Content.Post", "Post")
                        .WithMany("Features")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_add_feature_post_post_id");

                    b.Navigation("FeatureType");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Features.LikeLog", b =>
                {
                    b.HasOne("DhSport.Domain.Entities.Content.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_like_log_post_post_id");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Features.ReadLog", b =>
                {
                    b.HasOne("DhSport.Domain.Entities.Content.Post", "Post")
                        .WithMany("Reads")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_read_log_post_post_id");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Site.Menu", b =>
                {
                    b.HasOne("DhSport.Domain.Entities.Site.Menu", "ParentMenu")
                        .WithMany("ChildMenus")
                        .HasForeignKey("ParentMenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_menu_menu_parent_menu_id");

                    b.Navigation("ParentMenu");
                });

            modelBuilder.Entity("DhSport.Domain.Entities.UserManagement.UserRoleMap", b =>
                {
                    b.HasOne("DhSport.Domain.Entities.UserManagement.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_map_role_role_id");

                    b.HasOne("DhSport.Domain.Entities.UserManagement.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_map_user_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Content.Board", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Content.BoardType", b =>
                {
                    b.Navigation("Boards");
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Content.Comment", b =>
                {
                    b.Navigation("ChildComments");
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Content.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Features");

                    b.Navigation("Files");

                    b.Navigation("Likes");

                    b.Navigation("Reads");

                    b.Navigation("RelatedPostsFrom");

                    b.Navigation("RelatedPostsTo");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Content.PostType", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Features.FeatureType", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("DhSport.Domain.Entities.Site.Menu", b =>
                {
                    b.Navigation("ChildMenus");
                });

            modelBuilder.Entity("DhSport.Domain.Entities.UserManagement.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DhSport.Domain.Entities.UserManagement.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
